crud/crud/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
# blog안에 view를 임포트 해준다.
import blog.views
#이곳에 미디어 하겠습니다!
from django.conf import settings
from django.conf.urls.static import static
#이곳에 회원가입!
from account import views

urlpatterns = [
    # 주소창 끝에 /admin을 쳐서 접속할 수 있음. 
    path('admin/', admin.site.urls),
    #페이지 열자마자 바로 실행됨, blog폴더 안에 view.py안에 main이라는 함수를 적용시킨다. 이름은 main으로 할 것임.
    path('', blog.views.main, name='main'),
    #주소창 끝에 /write/create를 쳐서 접속할 수 있음, blog폴더 안에 view.py안에 create이라는 함수를 적용시킨다. 이름은 create으로 할 것임.
    path('write/create/', blog.views.create, name='create'),
    #주소창 끝에 /detail를 쳐서 접속할 수 있음, 특정 게시물을 가져오는 것이기 때문에 id를 지정해줌, blog폴더 안에 view.py안에 create이라는 함수를 적용시킨다. 이름은 detail으로 할 것임.
    path('detail/<str:id>/', blog.views.detail, name='detail'),
    #주소창 끝에 /edit를 쳐서 접속할 수 있음, 특정 게시물을 가져오는 것이기 때문에 id를 지정해줌,blog폴더 안에 view.py안에 edit이라는 함수를 적용시킨다. 이름은 edit으로 할 것임.
    path('edit/<str:id>/', blog.views.edit, name='edit'),
    #주소창 끝에 /delete를 쳐서 접속할 수 있음, 특정 게시물을 가져오는 것이기 때문에 id를 지정해줌,blog폴더 안에 view.py안에 delete이라는 함수를 적용시킨다. 이름은 delete으로 할 것임.
    path('delete/<str:id>/', blog.views.delete, name='delete'),
    #해시테그 url추가
    path('blog/hashtag/', blog.views.hashtagform, name='hashtag'),
    #검색기능
    path('blog/<int:hashtag_id>/search/', blog.views.search, name='search'),
    #로그인!!!
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/blog/models.py
# 장고 데이터베이스에서 모델(여기!)로 가져온다. 
from django.db import models
# 프로젝트에서 사용하는 user를 import하기 위해 settings를 가져온다!
from django.conf import settings


# Create your models here.

# 모델은 모다? 데이터를 저장할 수 있게 해주는 곳! 아래 Blog라는 클래스를 만들어 title, pub_date, writer, content속성을 갖도록 한다.
# 이것은 각각 제목, 날짜, 작성자, 콘텐츠(내용)을 뜻합니다.
# writer에 null을 방지하기위해 디폴트를 "닉네임을 입력하시오"로 설정해둠
#  모델을 변경한 뒤에는 makemigrations!
class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateField('date published')
    writer = models.CharField(max_length=15, default='닉네임을 입력해주세요')
    content = models.TextField()
    hashtags = models.ManyToManyField('Hashtag', blank=True)
    #이곳에 미디어 하겠슴다!
    image = models.ImageField(upload_to='images/', blank=True)
    

# def로 함수를 선언하고~ 모델 클래스의 객체를 그대로(self) 문자열(str)로 반환한다. 
# 만약 __str__(self) 이하가 없다면 글쓴대로 제목이 나오지 않음. Blog object라고 뜸.
    def __str__(self):
        return self.title

class Comment(models.Model):
    def __str__(self):
        return self.text

    post_id = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    text = models.CharField(max_length=50)

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

crud/blog/forms.py
# 장고에서 제공하는 forms기능을 사용하기 위해 import함
from django import forms
# models.py에서 Blog모델을 쓸 것이기 때문에 가져온다!
from .models import Blog, Comment, Hashtag

# postform이라는 이름의 클래스 생성
class PostForm(forms.ModelForm):
    # 클래스 안의 클래스!
    class Meta:
        # Blog라는 모델을 참고하여form을 만들었음!
        model = Blog
        # Blog라는 모델의 값 중 제목, 작성자, 콘텐츠 항목을 입력받을 것임
        fields = ['title', 'writer', 'content', 'hashtags', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

crud/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
# models.py에서 Blog모델을 쓸 것이기 때문에 가져온다!
from .models import Blog, Hashtag
#forms.py에서 PostForm를 가져온다.
from .forms import PostForm, CommentForm, HashtagForm #CommentForm 추가함, 해시태그폼도!
# 장고에서 제공하는 시간기능을 사용하기 위함!
from django.utils import timezone

# Create your views here.

# def로 함수선언~ main이란 이름의 함수는 요청받았을 때 
# models.py에 있는 Blog클래스로 만든 객체들을 posts라는 변수에 저장한다.
# 반환한다(return), 불러옴으로써(render) 요청받았을 때 (request), blog파일에 main.html이란 html파일을 띄운다!
# 그리고 posts라는 변수를 main.html로 넘길 때 posts라는 이름으로 넘기겠다!!
#메인페이지
def main(request):
    posts = Blog.objects
    #여기에 해시태그 검색 넣음
    hashtags = Hashtag.objects
    return render(request, 'blog/main.html', {'posts':posts, 'hashtags':hashtags})
    
# def로 함수선언~ write이란 이름의 함수는 요청받았을 때 
# 반환한다(return), 불러옴으로써(render) 요청받았을 때 (request), blog파일에 write.html이란 html파일을 띄운다!
#글쓰기페이지
def write(request):
    return render(request, 'blog/write.html')

#글쓰기 함수
# def로 함수선언~ create이란 이름의 함수는 요청받았을 때 
def create(request, blog=None):
    #view에서 다시 한번 method를 확인 한뒤
    if request.method == 'POST':
        # form의 입력값 유효성 검증을 시작
        #request.files (미디어) 추가
        form = PostForm(request.POST, request.FILES, instance=blog )
        #우리가 post형식으로 요청받은 form이 forms.py에서 작성받기로 한 정보를 다 받았는 지 유효성검사!
        if form.is_valid ():
           blog = form.save(commit=False)
           blog.pub_date = timezone.datetime.now()
           blog.save()
           form.save_m2m()

           return redirect('main')

    #그렇지 않는다면 폼을 다시 입력받음      
    else:
        form = PostForm
        return render(request, 'blog/write.html', {'form':form})

#수정페이지
def edit(request, id):
    #blog모델에서 id값을 Blog라는 변수에 담아 가져오려 하는데, id값을 제대로 가져오지 못하면 404에러를 일으킬 것.
    blog = get_object_or_404(Blog, id = id)
    #view에서 다시 한번 method를 확인 한뒤
    if request.method == "POST":
        #orm의 입력값 유효성 검증을 시작, 이때 instance는 수정할 글이 어떤 글인지 글의 id를 함수에게 설명
        form = PostForm(request.POST, instance=blog)
        if form.is_valid():
           form.save(commit=False)
           form.save()
           # 여기에 해시태그 했음#
           form.save_m2m()
           #form이 잘 입력되었다면 main으로 이동!
           return redirect('main')

    #그렇지 않는다면 폼을 다시 입력받음 
    else:
        form = PostForm(instance=blog)
        return render(request, 'blog/edit.html', {'form':form})
   

#삭제 함수
def delete(request, id):
    blog = get_object_or_404(Blog, id = id)
    #특정 id값을 가진 데이터를 삭제해주는 함수.
    blog.delete()
    
    #삭제를 한 다음에 다시 main페이지를 띄운다.
    return redirect('main')

#디테일
def detail(request, id):
    blog = get_object_or_404(Blog, id=id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment  = form.save(commit=False)
            comment.post_id = blog
            comment.text = form.cleaned_data['text']
            comment.save()
            form.save_m2m()
            return redirect('detail',id)
        
    else:
        form=CommentForm()
        return render(request, "blog/detail.html", {'post':blog, 'form':form})

#해시태그함수(제발 오타 노)
def hashtagform(request, hashtag=None):
    if request.method == 'POST':
        form = HashtagForm(request.POST, instance=hashtag)
        if form.is_valid():
            hashtag = form.save(commit=False)
            if Hashtag.objects.filter(name=form.cleaned_data['name']):
                form = HashtagForm()
                error_message = "이미 존재하는 해시태그 입니다."
                return render(request, 'blog/hashtag.html', {'form':form, "error_message": error_message})
            else:
                hashtag.name = form.cleaned_data['name']
                hashtag.save()
            #인덱스가 아니라 메인인가!?
            return redirect('main')
    else:
        form = HashtagForm(instance=hashtag)
        return render(request, 'blog/hashtag.html', {'form':form})

def search(request, hashtag_id):
    hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
    return render(request, 'blog/search.html', {'hashtag':hashtag})

crud/blog/templates/blog/base.html
<!--blog폴더에 있는 index.html의 형식을 그대로 이용하겠다!-->
{% extends 'blog/index.html' %} 
<!-- static폴더에 있는 css파일(이미지가 있다면 이미지도)을 불러와 사용하겠다!-->
{% load static %}

<!--content가 들어갈 자리를 만들어줌. 콘텐츠가 들어갈 자리를 빵꾸뚫어서 틀만 가져다 댄거라 생각하면 됨.
'block 무엇무엇'으로 시작하고 'endblock'으로 끝을 알려줌-->
{% block content %}
<h1>이곳은 베이스 일 뿐 당신들은 볼 수 없쒀 </h1>
{% endblock %}

crud/blog/templates/blog/detail.html
<!--blog폴더에 있는 base.html의 파일을 상속받겠다!-->
{% extends 'blog/base.html' %}
<!--static파일을 불러옴!-->
{% block content %}
<section class="page-section" id="services">
    <div class="container px-4 px-lg-5">

        <!--글제목을 넣을 예정입니다-->
        <!--작성 글을 보여주는 창! 제목과 작성일자, 작성자, 내용을 보여줌-->
        <h2 class="text-center mt-0">제목 : {{post.title}}</h2>
        <hr class="divider" />
        <p>작성 일자 및 시간 : {{ post.pub_date }}</p>
        <p>글쓴이 : {{ post.writer }}</p>
        <p>내용 : {{ post.content }}</p>

        <!--미디어 사진 확인!!!! -->
        {% if post.image %}
            <img src="{{ post.image.url }}" width="250" height="250" alt="Card image cap">
        {% endif %}
        <br>
        <!--여기에 해시태그 넣을게영!!!!-->
        {% for hashtag in post.hashtags.all %}
            <span>{{ hashtag.name }}</span>
        {% endfor %}
        <br>
        <!--edit.html로 이동할 것인데, 여러 post모델 중 특정 아이디만 받을 것.-->
        <a href="{% url 'edit' post.id %}">수정하기</a>
        <!--삭제 할것인데 여러 post모델 중 특정 아이디만 받아와 삭제.-->
        <a href="{% url 'delete' post.id %}">삭제하기</a>
        <br>
        <br>
        <br>
        {% for comment in post.comments.all %}
            <p>{{comment.text}}</p>
        {% endfor %}
        <form method="POST" action="{% url 'detail' post.id %}">
            {% csrf_token %}
            <p> {{ form.as_p }}</p>
            <input type="submit" value="submit">
        </form>
    </div>
</section>
{% endblock %}

crud/blog/templates/blog/edit.html
<!--blog폴더에 있는 base.html의 파일을 상속받겠다!-->
{% extends 'blog/base.html' %}

<!--content가 들어갈 자리를 만들어줌. 콘텐츠가 들어갈 자리를 빵꾸뚫어서 틀만 가져다 댄거라 생각하면 됨.
'block 무엇무엇'으로 시작하고 'endblock'으로 끝을 알려줌-->
{% block content %}
<!--작성 글을 보여주는 창!-->
<section class="page-section bg-primary" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">

                <!--CREATE FORM 들어갈 예정-->
                <!-- form은 정보를 입력 받을 수 있는 태그로, action과 method 속성을 가지고 있음
                action은 정보를 어디로 보내줄 것인지 설정하는 것이지만 form 사용시 장고가 html과 연결되어 있는 함수로 알아서 보내줌.
            따라서 action을 작성할 필요는 없다! 
            post방식을 통해 데이터를 보내줄 것임. post 방식은 데이터를 처리하여 보내줌. -->
                <form method="POST">
                    <!--공격으로부터 보호!-->
                    {% csrf_token %}
                    <table>
                        <!--forms.py에서 만든 form을 테이블 형식으로 가져오겠다!-->
                        {{form.as_table}}
                    </table>
                    <button class="btn btn-primary btn-xl" type="submit">작성</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

crud/blog/templates/blog/hashtag.html
{% extends 'blog/base.html' %}
<!--new.html은 N-M 강의 파일에서 가져옴! base.html을 상속받고 헤더바꿈!-->
{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('/static/app/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>New Hashtag</h1>
            <span class="subheading">해시태그를 추가하는 페이지입니다.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">
        {{ error_message }}
        <form method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input class="btn btn-dark" type="submit" value="제출하기">
        </form>
    </div>
</div>
{% endblock %}

crud/blog/templates/blog/index.html
<!--static파일을 불러옴!-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Creative - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'blog/assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">LIKELION9 AT SKHU</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <!-- main페이지로 연결!-->
                        <li class="nav-item"><a class="nav-link" href="{% url 'main' %}">main</a></li>
                        <!-- create페이지로 연결!-->
                        <li class="nav-item"><a class="nav-link" href="{% url 'create' %}">Create</a></li>
                        <!--해시태그 페이지 연결-->
                        <li class="nav-item"><a class="nav-link" href="{% url 'hashtag' %}">Add hashtag</a></li>
                        <!--회원가입!-->
                        {% if user.is_active %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">logout</a></li>
                            <li class="nav-item"><a class="nav-link">{{ user.username }}님 안녕하세요.</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">login</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">signup</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">LIKELION9</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">하하호호히히</p>
                        {% block createButton %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; LIKELION9 AT SKHU</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

crud/blog/templates/blog/main.html
<!--blog폴더에 있는 base.html의 파일을 상속받겠다!-->
{% extends 'blog/base.html' %} 
<!--content가 들어갈 자리를 만들어줌. base.html에서도 콘텐츠가 들어갈 자리를 빵꾸뚫어서 틀만 가져다 댄거라 생각하면 됨.
base.html의 콘텐츠가 들어가는 부분과 같은 부분에 main.html의 콘텐츠가 들어감!
'block 무엇무엇'으로 시작하고 'endblock'으로 끝을 알려줌-->
{% block content %}
<!--쓴 글을 보여주는 창(박스)를 만듦.-->
<a class="btn btn-primary btn-xl" href="{% url 'create' %}">CREATE</a>
<section class="page-section" id="services">
    <div class="container px-4 px-lg-5">
        <h2 class="text-center mt-0">READ</h2>
        <!--여기에 해시태그 검색기능 넣겠습니다!!!-->
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Hashtag 검색
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            {% for hashtag in hashtags.all %}
              <li><a class="dropdown-item" href="{% url 'search' hashtag.id %}">{{ hashtag.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
        {% for posts in posts.all %}
        <!--제목을 누르면 해당 id값을 가진 게시믈로 이동, 여기서 id는 고유번호!
        해당 게시물의 제목과, 작성자, 날짜와 시간을 가져올 것임. -->
        <p>제목 :<a href="{% url 'detail' posts.id %}">{{ posts.title }}</a></p>
        <p>작성자 : {{ posts.writer }}</p>
        <p>작성 일자 및 시간 : {{ posts.pub_date }}</p>
        <!--이곳에 미디어 구현!-->
        {% if posts.image %}
          <img src="{{ posts.image.url }}" width="250" height="250" alt="Card image cap">
        {% endif %}
        <hr>
        {% endfor %}
    </div>
</section>
{% endblock %}

crud/blog/templates/blog/search.html
{% extends 'blog/base.html' %}

{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('/static/app/img/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>{{ hashtag }}가 있는 게시글 목록</h1>
          <span class="subheading">해시태그 검색결과 페이지입니다.</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block content %}
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
    <!--blog 대신 post in ..으로 해야하나?!-->
    {% for post in hashtag.blog_set.all %}
    
      <div class="post-preview">
        <a href="{% url 'detail' post.id %}">
          <h2 class="post-title">
            {{ post.title }}
          </h2>
          <h3 class="post-subtitle">
            {{ post.summary }}
          </h3>
        </a>
        <p class="post-meta">
          {{ post.pub_date }}</p>
      </div>
      <hr>
      {% endfor %}
      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

crud/blog/templates/blog/write.html
<!--blog폴더에 있는 base.html의 파일을 상속받겠다!-->
{% extends 'blog/base.html' %}

<!--content가 들어갈 자리를 만들어줌. 콘텐츠가 들어갈 자리를 빵꾸뚫어서 틀만 가져다 댄거라 생각하면 됨.
'block 무엇무엇'으로 시작하고 'endblock'으로 끝을 알려줌-->
{% block content %}
<!--입력 창을 만들었음. -->
<section class="page-section bg-primary" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">

                <!--CREATE FORM 들어갈 예정-->
                <!-- form은 정보를 입력 받을 수 있는 태그로, action과 method 속성을 가지고 있음
                action은 정보를 어디로 보내줄 것인지 설정하는 것이지만 form 사용시 장고가 html과 연결되어 있는 함수로 알아서 보내줌.
            따라서 action을 작성할 필요는 없다! 
            post방식을 통해 데이터를 보내줄 것임. post 방식은 데이터를 처리하여 보내줌. -->
            <!--포스트 옆에 미디어폼 전송 추가함!-->
                <form method="POST" enctype="multipart/form-data">
                    <!--공격으로부터 보호!-->
                    {% csrf_token %}
                    <table>
                        <!--forms.py에서 만든 form을 테이블 형식으로 가져오겠다!-->
                        {{form.as_table}}
                    </table>
                    <!--버튼을 생성함, 버튼 누르면 제출!-->
                    <button class="btn btn-primary btn-xl" type="submit">작성</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}